plugins {
    id "java"
    id "checkstyle"
    id "io.quarkus"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 25
    options.compilerArgs.add("-parameters")
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

checkstyle {
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
    toolVersion = "14.1.0"
}

dependencies {
    implementation enforcedPlatform("io.quarkus.platform:quarkus-bom:3.33.3.2")

    implementation "io.quarkus:quarkus-rest-jackson"
    implementation "io.quarkus:quarkus-smallrye-health"
    implementation "io.quarkus:quarkus-config-yaml"
    implementation "io.quarkus:quarkus-agroal"
    implementation "io.quarkus:quarkus-flyway"
    implementation "org.jooq:jooq:3.21.8"
    runtimeOnly "org.xerial:sqlite-jdbc:3.53.4.0"

    testImplementation "io.quarkus:quarkus-junit5"
    testImplementation "io.rest-assured:rest-assured"
}
