FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

ARG APP_VERSION

WORKDIR /work/

RUN mkdir -p /data/state/.sqlite-tmp \
    && chown -R 1001:0 /work /data \
    && chmod -R "g+rwX" /work /data

COPY --chown=1001:0 --chmod=0755 build/server-${APP_VERSION}-runner /work/application

EXPOSE 8080

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dorg.sqlite.tmpdir=/data/state/.sqlite-tmp"]
