FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

WORKDIR /work/

RUN chown 1001:0 /work \
    && chmod "g+rwX" /work

COPY --chown=1001:0 --chmod=0755 build/*-runner /work/application

EXPOSE 8080

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dorg.sqlite.tmpdir=/data/state/.sqlite-tmp"]
